name: my-haskell-webapp
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - scotty
  - text
  - aeson

executables:
  my-haskell-webapp-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
